<?php
/**
 * ActivityModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * ActivityModelTest Class Doc Comment
 *
 * @category    Class */
// * @description ActivityModel
/**
 * @package     BumbalClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivityModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ActivityModel"
     */
    public function testActivityModel()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {

    }

    /**
     * Test attribute "activity_type_name"
     */
    public function testPropertyActivityTypeName()
    {

    }

    /**
     * Test attribute "activity_type_id"
     */
    public function testPropertyActivityTypeId()
    {

    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {

    }

    /**
     * Test attribute "status_name"
     */
    public function testPropertyStatusName()
    {

    }

    /**
     * Test attribute "instructions"
     */
    public function testPropertyInstructions()
    {

    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {

    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {

    }

    /**
     * Test attribute "top_priority"
     */
    public function testPropertyTopPriority()
    {

    }

    /**
     * Test attribute "send_invite"
     */
    public function testPropertySendInvite()
    {

    }

    /**
     * Test attribute "sequence_nr"
     */
    public function testPropertySequenceNr()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "date_time_from"
     */
    public function testPropertyDateTimeFrom()
    {

    }

    /**
     * Test attribute "date_time_to"
     */
    public function testPropertyDateTimeTo()
    {

    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {

    }

    /**
     * Test attribute "route_id"
     */
    public function testPropertyRouteId()
    {

    }

    /**
     * Test attribute "route_nr"
     */
    public function testPropertyRouteNr()
    {

    }

    /**
     * Test attribute "route_name"
     */
    public function testPropertyRouteName()
    {

    }

    /**
     * Test attribute "route_date_time_from"
     */
    public function testPropertyRouteDateTimeFrom()
    {

    }

    /**
     * Test attribute "route_date_time_to"
     */
    public function testPropertyRouteDateTimeTo()
    {

    }

    /**
     * Test attribute "route_earliest_date_time"
     */
    public function testPropertyRouteEarliestDateTime()
    {

    }

    /**
     * Test attribute "route_latest_date_time"
     */
    public function testPropertyRouteLatestDateTime()
    {

    }

    /**
     * Test attribute "route_status_id"
     */
    public function testPropertyRouteStatusId()
    {

    }

    /**
     * Test attribute "route_status_name"
     */
    public function testPropertyRouteStatusName()
    {

    }

    /**
     * Test attribute "route_nr_of_stops"
     */
    public function testPropertyRouteNrOfStops()
    {

    }

    /**
     * Test attribute "route_overdue"
     */
    public function testPropertyRouteOverdue()
    {

    }

    /**
     * Test attribute "driver_id"
     */
    public function testPropertyDriverId()
    {

    }

    /**
     * Test attribute "driver_first_name"
     */
    public function testPropertyDriverFirstName()
    {

    }

    /**
     * Test attribute "driver_last_name"
     */
    public function testPropertyDriverLastName()
    {

    }

    /**
     * Test attribute "driver_name_prefix"
     */
    public function testPropertyDriverNamePrefix()
    {

    }

    /**
     * Test attribute "driver_full_name"
     */
    public function testPropertyDriverFullName()
    {

    }

    /**
     * Test attribute "driver_email"
     */
    public function testPropertyDriverEmail()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {

    }

    /**
     * Test attribute "package_lines"
     */
    public function testPropertyPackageLines()
    {

    }

    /**
     * Test attribute "time_slots"
     */
    public function testPropertyTimeSlots()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

    /**
     * Test attribute "communication"
     */
    public function testPropertyCommunication()
    {

    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {

    }

    /**
     * Test attribute "meta_data_objects"
     */
    public function testPropertyMetaDataObjects()
    {

    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {

    }

}
