<?php
/**
 * NoteModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * NoteModelTest Class Doc Comment
 *
 * @category    Class */
// * @description NoteModel
/**
 * @package     BumbalClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NoteModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "NoteModel"
     */
    public function testNoteModel()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "object_type"
     */
    public function testPropertyObjectType()
    {

    }

    /**
     * Test attribute "object_type_name"
     */
    public function testPropertyObjectTypeName()
    {

    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {

    }

    /**
     * Test attribute "object_link"
     */
    public function testPropertyObjectLink()
    {

    }

    /**
     * Test attribute "note_category_id"
     */
    public function testPropertyNoteCategoryId()
    {

    }

    /**
     * Test attribute "note_category_name"
     */
    public function testPropertyNoteCategoryName()
    {

    }

    /**
     * Test attribute "visible_for_driver"
     */
    public function testPropertyVisibleForDriver()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "updated_by_name"
     */
    public function testPropertyUpdatedByName()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

    /**
     * Test attribute "note_created_at"
     */
    public function testPropertyNoteCreatedAt()
    {

    }

    /**
     * Test attribute "note_updated_at"
     */
    public function testPropertyNoteUpdatedAt()
    {

    }

    /**
     * Test attribute "note_created_by"
     */
    public function testPropertyNoteCreatedBy()
    {

    }

    /**
     * Test attribute "note_updated_by"
     */
    public function testPropertyNoteUpdatedBy()
    {

    }

}
