<?php
/**
 * PackageLineModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * PackageLineModelTest Class Doc Comment
 *
 * @category    Class */
// * @description PackageLineModel
/**
 * @package     BumbalClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackageLineModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PackageLineModel"
     */
    public function testPackageLineModel()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {

    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {

    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {

    }

    /**
     * Test attribute "nr_of_packages"
     */
    public function testPropertyNrOfPackages()
    {

    }

    /**
     * Test attribute "package_type_name"
     */
    public function testPropertyPackageTypeName()
    {

    }

    /**
     * Test attribute "package_type_id"
     */
    public function testPropertyPackageTypeId()
    {

    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {

    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {

    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {

    }

    /**
     * Test attribute "unit_volume"
     */
    public function testPropertyUnitVolume()
    {

    }

    /**
     * Test attribute "net_weight_unit"
     */
    public function testPropertyNetWeightUnit()
    {

    }

    /**
     * Test attribute "net_weight_total"
     */
    public function testPropertyNetWeightTotal()
    {

    }

    /**
     * Test attribute "tare_weight_unit"
     */
    public function testPropertyTareWeightUnit()
    {

    }

    /**
     * Test attribute "tare_weight_total"
     */
    public function testPropertyTareWeightTotal()
    {

    }

    /**
     * Test attribute "gross_weight_unit"
     */
    public function testPropertyGrossWeightUnit()
    {

    }

    /**
     * Test attribute "gross_weight_total"
     */
    public function testPropertyGrossWeightTotal()
    {

    }

    /**
     * Test attribute "unit_loading_meter"
     */
    public function testPropertyUnitLoadingMeter()
    {

    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {

    }

    /**
     * Test attribute "adr"
     */
    public function testPropertyAdr()
    {

    }

    /**
     * Test attribute "adr_class"
     */
    public function testPropertyAdrClass()
    {

    }

    /**
     * Test attribute "adr_un_nr"
     */
    public function testPropertyAdrUnNr()
    {

    }

    /**
     * Test attribute "temp"
     */
    public function testPropertyTemp()
    {

    }

    /**
     * Test attribute "temp_min"
     */
    public function testPropertyTempMin()
    {

    }

    /**
     * Test attribute "temp_max"
     */
    public function testPropertyTempMax()
    {

    }

    /**
     * Test attribute "capacity_volume"
     */
    public function testPropertyCapacityVolume()
    {

    }

    /**
     * Test attribute "capacity_loading_meter"
     */
    public function testPropertyCapacityLoadingMeter()
    {

    }

    /**
     * Test attribute "capacity_loading_weight"
     */
    public function testPropertyCapacityLoadingWeight()
    {

    }

    /**
     * Test attribute "hs_code"
     */
    public function testPropertyHsCode()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

    /**
     * Test attribute "activity_links"
     */
    public function testPropertyActivityLinks()
    {

    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {

    }

    /**
     * Test attribute "meta_data_objects"
     */
    public function testPropertyMetaDataObjects()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

}
