<?php
/**
 * RouteModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * RouteModelTest Class Doc Comment
 *
 * @category    Class */
// * @description RouteModel
/**
 * @package     BumbalClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RouteModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RouteModel"
     */
    public function testRouteModel()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "status_name"
     */
    public function testPropertyStatusName()
    {

    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {

    }

    /**
     * Test attribute "nr_of_stops"
     */
    public function testPropertyNrOfStops()
    {

    }

    /**
     * Test attribute "driver_id"
     */
    public function testPropertyDriverId()
    {

    }

    /**
     * Test attribute "driver_link"
     */
    public function testPropertyDriverLink()
    {

    }

    /**
     * Test attribute "car_id"
     */
    public function testPropertyCarId()
    {

    }

    /**
     * Test attribute "car_link"
     */
    public function testPropertyCarLink()
    {

    }

    /**
     * Test attribute "trailer_id"
     */
    public function testPropertyTrailerId()
    {

    }

    /**
     * Test attribute "trailer_link"
     */
    public function testPropertyTrailerLink()
    {

    }

    /**
     * Test attribute "earliest_date_time"
     */
    public function testPropertyEarliestDateTime()
    {

    }

    /**
     * Test attribute "latest_date_time"
     */
    public function testPropertyLatestDateTime()
    {

    }

    /**
     * Test attribute "gps_locations"
     */
    public function testPropertyGpsLocations()
    {

    }

    /**
     * Test attribute "latest_known_position"
     */
    public function testPropertyLatestKnownPosition()
    {

    }

    /**
     * Test attribute "recurrence_id"
     */
    public function testPropertyRecurrenceId()
    {

    }

    /**
     * Test attribute "recurrence_nr"
     */
    public function testPropertyRecurrenceNr()
    {

    }

    /**
     * Test attribute "overdue"
     */
    public function testPropertyOverdue()
    {

    }

    /**
     * Test attribute "blocked"
     */
    public function testPropertyBlocked()
    {

    }

    /**
     * Test attribute "start_address"
     */
    public function testPropertyStartAddress()
    {

    }

    /**
     * Test attribute "end_address"
     */
    public function testPropertyEndAddress()
    {

    }

    /**
     * Test attribute "activity_ids"
     */
    public function testPropertyActivityIds()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

}
