<?php
/**
 * ZoneModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * ZoneModelTest Class Doc Comment
 *
 * @category    Class */
// * @description ZoneModel
/**
 * @package     BumbalClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ZoneModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ZoneModel"
     */
    public function testZoneModel()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "filter_tag_names"
     */
    public function testPropertyFilterTagNames()
    {

    }

    /**
     * Test attribute "filter_tags"
     */
    public function testPropertyFilterTags()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {

    }

    /**
     * Test attribute "zone_ranges"
     */
    public function testPropertyZoneRanges()
    {

    }

    /**
     * Test attribute "zone_created_at"
     */
    public function testPropertyZoneCreatedAt()
    {

    }

    /**
     * Test attribute "zone_updated_at"
     */
    public function testPropertyZoneUpdatedAt()
    {

    }

    /**
     * Test attribute "zone_created_by"
     */
    public function testPropertyZoneCreatedBy()
    {

    }

    /**
     * Test attribute "zone_updated_by"
     */
    public function testPropertyZoneUpdatedBy()
    {

    }

}
