<?php
/**
 * PackagetypeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * PackagetypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PackagetypeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createPackageType
     *
     * Create or update an Package Line.
     *
     */
    public function testCreatePackageType()
    {

    }

    /**
     * Test case for deletePackageType
     *
     * Delete an package-type.
     *
     */
    public function testDeletePackageType()
    {

    }

    /**
     * Test case for retrieveListPackageType
     *
     * Retrieve List of PackageTypes.
     *
     */
    public function testRetrieveListPackageType()
    {

    }

    /**
     * Test case for retrievePackageType
     *
     * Find package-type by ID.
     *
     */
    public function testRetrievePackageType()
    {

    }

    /**
     * Test case for setPackageType
     *
     * Set (create or update) an PackageType.
     *
     */
    public function testSetPackageType()
    {

    }

    /**
     * Test case for updatePackageType
     *
     * Update a package-type.
     *
     */
    public function testUpdatePackageType()
    {

    }

}
